// <auto-generated />
namespace VETPRO2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _428 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_428));
        
        string IMigrationMetadata.Id
        {
            get { return "201604290312461_4.28"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
